### ISSUE TITLE
Qlot does not work on CCL in OSX

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/qlot#39] opened 2017-04-04 19:54 UTC
I'm trying to use qlot with CCL. But it outputs an error:

```
[art@art-osx5:.../lisp/cl-bitbar-startrek]% qlot help                                                           b:master s:
> Error: There is no package named "ASDF" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry finding package with name "ASDF".
> Type :? for other options.
1 > :B
 (210668B8) : 0 (%PARSE-TOKEN #<STRING-INPUT-STREAM  #x3020004EA13D> #\a NIL) 1565
 (21066960) : 1 (%PARSE-EXPRESSION #<STRING-INPUT-STREAM  #x3020004EA13D> #\a NIL) 245
 (210669B8) : 2 (%READ-FORM #<STRING-INPUT-STREAM  #x3020004EA13D> 0 NIL) 573
 (210669F8) : 3 (READ-INTERNAL #<STRING-INPUT-STREAM  #x3020004EA13D> T NIL NIL) 253
 (21066A78) : 4 (READ #<STRING-INPUT-STREAM  #x3020004EA13D> T NIL NIL) 157
 (21066AC8) : 5 (READ-FROM-STRING "asdf::eval-input" T NIL :START 0 :END NIL :PRESERVE-WHITESPACE NIL) 413
 (21066B70) : 6 (FUNCALL #'#<(:INTERNAL ROSWELL::BODY ROSWELL:SCRIPT)> #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/art/.roswell/bin/qlot"/4 UTF-8) #x3020004EA55D>) 221
 (21066BD0) : 7 (SCRIPT :SCRIPT "/Users/art/.roswell/bin/qlot" "help") 501
 (21066C50) : 8 (RUN ((:SCRIPT "/Users/art/.roswell/bin/qlot" "help") (:QUIT NIL))) 213
 (21066C88) : 9 (CALL-CHECK-REGS ROSWELL:RUN ((:SCRIPT "/Users/art/.roswell/bin/qlot" "help") (:QUIT NIL))) 221
 (21066CC0) : 10 (CHEAP-EVAL (ROSWELL:RUN '#)) 101
 (21066CF8) : 11 (FUNCALL #'#<(:INTERNAL CCL::EVAL-STRING CCL::STARTUP-CCL)> "(ros:run '((:script \"/Users/art/.roswell/bin/qlot\"\"help\")(:quit ())))") 485
 (21066D40) : 12 (STARTUP-CCL NIL) 1541
 (21066DA8) : 13 (FUNCALL #'#<(:INTERNAL (TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T)))>) 61
 (21066DC8) : 14 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (21066E60) : 15 (RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x3020004563ED> (#<COMPILED-LEXICAL-CLOSURE # #x302000455F1F>)) 669
 (21066EF0) : 16 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<TTY-LISTENER listener(1) [Active] #x3020004563ED> (#<COMPILED-LEXICAL-CLOSURE # #x302000455F1F>)) 573
 (21066F98) : 17 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277
```

Qlot is fresh and was installed today from github repository like `ros install fukamachi/qlot`.
CCL was installed via roswell and have version `Version 1.11-r16635  (DarwinX8664)`.

**Comment by fukamachi** [comment] 2017-05-09 02:41
I cannot reproduce it.
What version of Roswell are you using?

**Comment by svetlyak40wt** [comment] 2017-05-09 14:57
I have 17.2.8.74(5e7907c) version.

**Comment by fukamachi** [comment] 2017-05-10 03:46
Thanks.

@snmsts Do you have any ideas?

**Comment by snmsts** [comment] 2017-05-10 04:00
not really.

**Comment by snmsts** [comment] 2017-05-10 04:05
for now.

```
(ensure-asdf)
```

in ``~/.roswell/init.lisp`` will fix the problem.

**Comment by svetlyak40wt** [comment] 2017-05-10 04:39
Here more details:
```
[art@art-osx5:~]% ros run
Welcome to Clozure Common Lisp Version 1.11-r16635  (DarwinX8664)!

CCL is developed and maintained by Clozure Associates. For more information
about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common Lisp
consulting services e-mail info@clozure.com or visit http://www.clozure.com.

? (asdf:asdf-version)
"3.1.5"
```

**Comment by svetlyak40wt** [comment] 2017-05-10 04:40
@snmsts I tried to add a line to `init.lisp` and must admit that it fixes the problem. Thank you.

**Comment by snmsts** [comment] 2017-05-10 04:43
wait and see the next roswell release :)

**Comment by fukamachi** [comment] 2017-05-10 10:05
Closing.

**Closed by fukamachi** 2017-05-10 10:05 UTC
